k-bot:
  token: "your bot token"
  cmd: "!koy"
  # register plugins
  plugins:
  - time
  - joker
  - player

  # register listeners
  listeners:
  - kbot
  - member

  introduction:
    location: classpath:introduction.md